n = input('Digite algo: ')
print('Qual o tipo da variavel?',type(n))
print('O que eu digitei so tem espaços??', n.isspace())
print('O que eu digitei é somente numero??',n.isnumeric())
print('O que eu digitei é somente alfabeto??',n.isalpha())
print('O que eu digitei é alfanumero??',n.isalnum())
print('O que eu digitei está em letras maiusculas?',n.isupper())
print('O que eu digitei está em letras minusculas?',n.islower())
print('O que eu digitei está capitalizada?',n.istitle())
